function thisIsMadness(){if(sColorScheme="",bShowWelcome=!1,location.hash.length>0){var e=location.hash.replace("#","")
location.hash.indexOf("styles-")>-1&&(sColorScheme=e),location.hash.indexOf("welcome")>-1&&(bShowWelcome=!0)}if(sColorScheme||(sColorScheme=Cookies.get("ht-colorscheme")),null!=sColorScheme){var t="css/"+sColorScheme+".css"
$("link#theme-styles").attr("href",t)}else sColorScheme="styles-bluegreen"
history.replaceState(void 0,void 0,"#"+sColorScheme),document.write('<style class="tempStyle">#'+sColorScheme+" {background:#646464;}</style>"),bHideSwitcher=Cookies.get("ht-hideSwitcher"),bHideSwitcher||(document.write('<style class="tempStyle">#settings-panel {display: block}</style>'),document.write('<style class="tempStyle">.settings-toggle {background-color:#e9e9e9;}</style>'),document.write('<style class="tempStyle">.settings-toggle a {color:#37424c}</style>'))}function refreshAfterHashChange(){var e=location.hash.replace("#","")
if(isFirstPick=!Cookies.get("ht-firstPickMade"),location.hash.length>0){if(e.indexOf("styles-")>-1){var t="css/"+e+".css"
$("link#theme-styles").attr("href",t),$(".settings-panel").children(".theme").each(function(){$(this).removeClass("active")}),$("#"+e).addClass("active"),Cookies.set("ht-colorscheme",e)}location.hash.indexOf("welcome")>-1?$("#welcomeScreen").show():$("#welcomeScreen").hide({duration:400})}}function shuffleArray(e){for(var t=e.length-1;t>0;t--){var s=Math.floor(Math.random()*(t+1)),o=e[t]
e[t]=e[s],e[s]=o}return e}$(function(){if(window.onhashchange=function(){refreshAfterHashChange()},$("style.tempStyle").remove(),isFirstPick=!Cookies.get("ht-firstPickMade"),isFirstPick){var e=[]
$(".schemeShowcase").each(function(){e.push($(this).html()),$(this).html("")}),shuffleArray(e),$(".schemeShowcase").each(function(){$(this).html(e.pop())})}bShowWelcome&&(window.location.hash="welcome"),$("#welcomeScreen .schemeSelect .scheme").each(function(){$(this).click(function(){if($(window).scrollTop(0),isFirstPick){var e=$(this).attr("href").replace("#","")
ga("send",{hitType:"event",eventCategory:"Initial Scheme Selection",eventAction:e}),Cookies.set("ht-firstPickMade",!0,{expires:30})}return!0})}),null==Cookies.get("ht-hideSwitcher")&&($(".settings-panel").addClass("toggled"),$(".settings-toggle").addClass("toggled")),$(".settings-toggle .toggle").click(function(){return $(".settings-panel").fadeToggle({duration:400}),$(".settings-toggle").hasClass("toggled")===!1?($(".settings-toggle").addClass("toggled"),$(".settings-panel").addClass("toggled"),Cookies.remove("ht-hideSwitcher")):($(".settings-panel").removeClass("toggled"),$(".settings-toggle").removeClass("toggled"),Cookies.set("ht-hideSwitcher",!0)),!1}),refreshAfterHashChange(),setTimeout(function(){$(".settings-panel").height($(document).height()-70),$("#welcomeScreen").height($(document).height())},500)})
